### ISSUE TITLE
Urgent orders

### ISSUE THREAD

**Issue by adz35** [cbx33/garzolean#1]
Needs to hold its position in the top left so its easily seen. Also if it could be a different colour (primary) for the duration of its time until (success) is needed.

**Comment by cbx33** [comment]
So basically override the colour all the time it has an urgent flag??

**Comment by adz35** [comment]
Yeah thats right. So it stays urgent colour all through the stages until you want to change it to the ready stage. Obviously you will still see its urgent due to the urgent flag.

**Comment by cbx33** [comment]
Makes sense
